<?php
// $Id: $

/**
 * @file
 * Extend FileField to allow files to have Creative Commons licences attached to them.
 */

function filefield_license_menu() {
  $items = array();
  $items['admin/settings/filefield-license'] = array(
    'title' => 'Filefield Creative Commons',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('filefield_license_settings'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

//----------------------------------------------------------------------

/**
 * Implementation of hook_widget_settings_alter(). The less docummented hook!
 * 
 */
function filefield_license_widget_settings_alter(&$settings, $op, $widget) {
  $widget_type = isset($widget['widget_type']) ? $widget['widget_type'] : $widget['type'];
  
  
  if ($op == 'form') {
    $settings['license'] = array(
      '#type' => 'select',
      '#title' => t('Licensing'),
      '#options' => array(
        t('Do not collect'),
        t('Possible'),
        t('Required'),
      ),
      '#default_value' => $widget['license'],
    );
  }

  if ($op == 'save') {
    $settings[] = 'license';
  }
}

function filefield_license_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['#node']) && isset($form['type']['#value']) && $form_id == $form['type']['#value'] .'_node_form') {
    $form['#after_build'][] = 'filefield_license_after_build';
    $form['#submit'][] = 'filefield_license_item_submit';
  }
}




function filefield_license_after_build($form, &$form_state) {
  foreach (element_children($form) as $key) {
    if ($form[$key]['#field_name']) {
      $field = content_fields($form[$key]['#field_name'], $form['#node']->type);
      if ($field['module'] == 'filefield' && $field['widget']['license']) {
        filefield_license_widget_form_alter($form[$key], $form_state, $field, $form['#node']);
      }
    }
  }
  return $form;
}

function filefield_license_widget_form_alter(&$element, &$form_state, $field, $node) {
  
  foreach (element_children($element) as $delta) {
    if (is_numeric($delta)) {
      filefield_license_item_form_alter($element[$delta], $form_state, $field, $delta, $node);
    }
  }
}

function filefield_license_item_form_alter(&$element, &$form_state, $field, $delta, $node) {
  
  if (isset($element['license'])) {
    return;
  }
  
  ctools_include('dependent');
  $license_id = $element['#id'] .'-data-license';
  $info = isset($form_state['values'][$field['field_name']][$delta]['data']['license']) ? $form_state['values'][$field['field_name']][$delta]['data']['license'] : $node->{$field['field_name']}[$delta]['data']['license'];
  
  if (is_array($element['#default_value']['data'])) {
    $element['#default_value']['data']['license'] = $info;
  }
  
  
  $license_el = array(
    '#parents' => array_merge($element['data']['#parents'], array('license')),
    '#array_parents' => array_merge($element['data']['#array_parents'], array('license')),
    
    '#default_value' => $info,
    '#tree' => TRUE,
    
    '#id' => $license_id,
    
    'name' => array(
      '#parents' => array_merge($element['data']['#parents'], array('license', 'name')),
      '#array_parents' => array_merge($element['data']['#array_parents'], array('license', 'name')),
      
      '#title' => t('License'),
      '#weight' => -100,
      '#type' => 'select',
      '#options' => license_form_options(),
      
      '#id' => $license_id .'-name',
      '#name' => $element['#name'] .'[data][license][name]',
      
      '#value' => $info['name'],
    ),
  );
  
  foreach (license_load() as $name => $license) {
    $license->additional_fields = is_string($license->additional_fields) ? unserialize($license->additional_fields) : $license->additional_fields;
    if (!is_array($license->additional_fields)) {
      continue;
    }
    foreach ($license->additional_fields as $additional => $fapi) {
      if (!isset($license_el[$additional])) {
        
        $html_id = $license_id .'-'. preg_replace('/[^a-zA-Z0-9-]+/', '-', $additional);
        
        $license_el[$additional] = array_merge($fapi, array(
          '#parents' => array_merge($element['data']['#parents'], array('license', $additional)),
          '#array_parents' => array_merge($element['data']['#array_parents'], array('license', $additional)),
          
          '#prefix' => '<div id="'. $html_id .'-wrapper">'. $fapi['#prefix'],
          '#suffix' => $fapi['#suffix'] .'</div>',
          '#process' => array('ctools_dependent_process'),

          '#id' => $html_id,
          '#name' => $element['#name'] .'[data][license]['. check_plain($additional) .']',
        ));
        
      }
    
      if (!$license_el[$additional]['#value'] && $info[$additional]) {
        $license_el[$additional]['#value'] = $info[$additional];
      }
      
      $license_el[$additional]['#dependency'][$license_id .'-name'] = is_array($license_el[$additional]['#dependency'][$license_id .'-name']) ? $license_el[$additional]['#dependency'][$license_id .'-name'] : array();
      if (!in_array($name, $license_el[$additional]['#dependency'][$license_id .'-name'])) {
        $license_el[$additional]['#dependency'][$license_id .'-name'][] = $name;
      }
    }
  }
  
  foreach (element_children($license_el) as $key) {
    if (isset($license_el[$key]['#dependency']) && count($license_el[$key]['#dependency'])) {
      $pseudo_form = array();
      $license_el[$key] = ctools_dependent_process($license_el[$key], $info, $form_state, $pseudo_form);
    }
  }
  
  $element['data']['license'] = $license_el;
  form_set_value($element['data']['license'], $info, $form_state);
}

function filefield_license_item_submit($form, &$form_state) {
  
  
  foreach (content_fields(NULL, $form['#node']->type) as $field) {
    if ($field['module'] != 'filefield' || empty($field['widget']['license'])) {
      continue;
    }
    
    $field_value = &$form_state['values'][$field['field_name']];
    
    foreach ($field_value as $delta => $delta_value) {
      if (is_numeric($delta) && is_array($delta_value['data'])) {
        $field_value[$delta]['data']['license'] = $delta_value['data']['license'];
      }
    }
    
  }
  
  
}


//----------------------------------------------------------------------

function filefield_license_other_formatters() {
  static $formatters = array();
  
  if (!empty($formatter)) {
    return $formatter;
  }
  
  foreach (module_implements('field_formatter_info') as $module) {
    if ($module == 'filefield_license') {
      continue;
    }
    $hook = $module .'_field_formatter_info';
    foreach ($hook() as $formatter => $info) {
      if (in_array('filefield', $info['field types']) || in_array('image', $info['field types'])) {
        $info['module'] = $module;
        $formatters[$formatter] = $info;
      }
    }
  }
  return $formatters;
}

/**
 * Implementation of hook_field_formatter_info().
 */
function filefield_license_field_formatter_info() {
  $formatters = array();
  
  foreach (filefield_license_other_formatters() as $formatter => $info) {
    $formatters['licensed__'. $info['module'] .'__'. $formatter] = $info;
    $formatters['licensed__'. $info['module'] .'__'. $formatter]['label'] = t('Licensed: @formatter_label', array('@formatter_label' => $info['label']));
  }
  
  return $formatters;
}


function filefield_license_theme() {
  $hooks = array();
  $pattern = 'filefield_license_formatter_licensed__';
  
  foreach (filefield_license_other_formatters() as $formatter => $info) {
    $hooks[$pattern . $info['module'] .'__'. $formatter] = array(
      'function' => 'theme_filefield_license_formatter',
      'arguments' => array('element' => NULL),
    );
  }

  return $hooks;
}


function theme_filefield_license_formatter($element) {
  $hook = explode('__', $element['#formatter']);
  array_shift($hook);
  $module = array_shift($hook);
  $formatter = $module .'_formatter_'. implode('__', $hook);
  $element['#formatter'] = implode('__', $hook);
//  dpm(array(
//    'module' => $module,
//    'formatter' => $formatter,
//  ));
  return theme($formatter, $element) . theme('license_button_by_name', $element['#item']['data']['license']['name'], '80x15', $element['#item']['data']['license']);
}